### ISSUE TITLE
Installation help for newbies

### ISSUE THREAD

**Issue by cruepprich** [tonyp7/esp32-wifi-manager#10]
Hi,
I'm new to ESP32 development. I use the Arduino IDE, and would like to know how to use the Wifi manager with it.

thanks!

**Comment by tonyp7** [comment]
Hello,
You can't use Arduino IDE. This is a pure native esp-idf project and needs to be compiled with the SDK toolchain. If you feel adventurous go there: http://esp-idf.readthedocs.io/en/latest/get-started/index.html
