### ISSUE TITLE
httpd_parse: parse_block: request URI/header too long

### ISSUE THREAD

**Issue by hackaprende** [tonyp7/esp32-wifi-manager#127]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of esp32-wifi-manager
- [ x] I have searched [open](https://github.com/tonyp7/esp32-wifi-manager/issues) and [closed](https://github.com/tonyp7/esp32-wifi-manager/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I run the project I get this error

![image](https://user-images.githubusercontent.com/5779511/112256510-82be7600-8c29-11eb-9bef-c7c144156860.png)

The same is displayed in the browser

### Steps to Reproduce

- Add esp32-wifi-manager as component
- Call 	wifi_manager_start(); in app_main
- Connect to esp32
- "Header fields are too long for server to interpret" error appears

### System Configuration

- Environment (Operating system, version and so on): Esp32 devkitC with IDF V4.2, in MacOS
- Additional information:

**Comment by hackaprende** [comment]
It happens in brave and duck duck go browsers in Android. It works well for Chrome

**Comment by tofublock** [comment]
Why did you close this issue? Did you find a solution or did you give up on it?
I'm facing the same issue on Android 11 - the captive portal opens a (system?) browser window saying "Header fields are too long for server to interpret". If I choose "Use this network as is" I can SOMETIMES get Firefox or Chrome to load 10.10.0.1 but most of the time it won't load or the network just disconnects.
Can somebody help? Where can I start looking?
Thanks!

**Comment by tofublock** [comment]
Okay, for anyone coming after me -
set `idf.py menuconfig > Component config > HTTP Server > Max HTTP URI Length` to `1024` and the captive portal comes up right away. I'm still frequently seeing strange disconnects, but that's a separate issue.

**Comment by daverathbone** [comment]
Just a lot of pain to find you use J and K keys for up down arrow - Make it harder!!!!!
