### ISSUE TITLE
Editing the captive http portal to use own images and styles

### ISSUE THREAD

**Issue by markirwin** [tonyp7/esp32-wifi-manager#134]
I have modified the src index.html to include a logo and included an image tag in the HTML. However this doesn't work when serving the portal?? I think the logo file needs to be included somewhere so it becomes available?

I also want to add my own custom fields to be saved on NVS do I need to create a separate page to do this or can I modify the portal page?

**Comment by oachkatzalschwoaf** [comment]
for your additional files you might check:
(depending on your Build system):
`CMakeLists.txt` -   
5. `EMBED_FILES src/style.css src/code.js src/index.html   ADD_YOUR_NEW_FILES_HERE)`  
and 
10. `set(COMPONENT_EMBED_FILES src/style.css src/code.js src/index.html  ADD_YOUR_NEW_FILES_HERE)`

and/or 

`component.mk` - 
 4. `COMPONENT_EMBED_FILES := src/style.css src/code.js src/index.html ADD_YOUR_NEW_FILES_HERE` 


and you also have to serve your new files im http_app.c
