### ISSUE TITLE
wifi_manager_destroy never gets called?

### ISSUE THREAD

**Issue by snahmad** [tonyp7/esp32-wifi-manager#15]

**Comment by tonyp7** [comment]
That's correct. This function was created as a sanity to clean up properly the memory in case you would like to completely shutdown wifi_manager; but in this implementation the wifi_manager task is always on.

This function is here to help you integrate wifi_manager with your existing codebase.

**Comment by snahmad** [comment]
ok.

**Comment by snahmad** [comment]
wifi_config_t* wifi_manager_config_sta is not thread safe. not sure how can i do it in C. I know C++ atomic.

**Comment by tonyp7** [comment]
The equivalent in freeRTOS is xSemaphoreTake/xSemaphoreGive. Can you point me to a potential unsafe code location?

**Comment by snahmad** [comment]
ok, Thanks. While OTA update I need to stop my Http server. that will do trick
