### ISSUE TITLE
Implementing into project with ulp.

### ISSUE THREAD

**Issue by forthe94** [tonyp7/esp32-wifi-manager#16]
Hello, thank you for great wifi manager!

I've got an issue, when I'm trying to append wifi manager to program with ULP I catch error with undefined reference

/home/tetenkov/esp/esp32-wifi-manager/wifi_manager/build/main/libmain.a(baremetal.o):(.literal.init_ulp_program+0x0): undefined reference to `_binary_ulp_app_bin_end'
/home/tetenkov/esp/esp32-wifi-manager/wifi_manager/build/main/libmain.a(baremetal.o):(.literal.init_ulp_program+0x4): undefined reference to `_binary_ulp_app_bin_start'

I really change nothing in ULP programming logic, I follow Programming Guide but when I add wifi manager files it fails.

**Comment by tonyp7** [comment]
undefined reference to _binary_ulp_app_bin_start means you haven't included all necessary libraries in your app.
I'm marking this as unrelated to the wifi manager.
Thanks for the kind message!
