### ISSUE TITLE
Error when trying to configure the AP-AP/STA settings

### ISSUE THREAD

**Issue by willeww8** [tonyp7/esp32-wifi-manager#19]
Whenever I change the value in the header file Wifi_manager for the AP or AP/STA config, the program breaks and throws this error:

> 
> ****ESP_ERROR_CHECK failed: esp_err_t 0xb (ERROR) at 0x400d397b
> 0x400d397b: wifi_manager at /home/will/esp/esp32-wifi-manager/wifi_manager/main/wifi_manager.c:527 (discriminator 1)
> 
> file: "/home/will/esp/esp32-wifi-manager/wifi_manager/main/wifi_manager.c" line 527
> func: wifi_manager
> expression: esp_wifi_set_config(WIFI_IF_AP, &ap_config)
> 
> Backtrace: 0x4008e78c:0x3ffbe9e0 0x4008ec3c:0x3ffbea00 0x400d397b:0x3ffbea20
> 0x4008e78c: invoke_abort at /home/will/esp/esp-idf/components/esp32/panic.c:649****

Even trying to change the value back and reflashing the board doesnt fix it. Any ideas?

**Comment by tonyp7** [comment]
wifi manager now handles properly switches between AP and AP/STA. You should try out the latest master branch.
