### ISSUE TITLE
dynamic or static ram

### ISSUE THREAD

**Issue by snahmad** [tonyp7/esp32-wifi-manager#22]
Hi tony,

Does this wifi manage uses dynamic ram allocaton for wifi or static.
Where in the code I can specify not to use dynamic ram.

in my menuconfig I specify only static ram. I don't want to use dynamic ram for wifi.

but my debug logs on startup shows some dynamic ram allocations.

I (1105) wifi: Init dynamic tx buffer num: 32
I (1108) wifi: Init data frame dynamic rx buffer num: 64
I (1113) wifi: Init management frame dynamic rx buffer num: 64
I (1119) wifi: Init static tx buffer num: 12
I (1123) wifi: Init static rx buffer size: 1600
I (1127) wifi: Init static rx buffer num: 12
I (1131) wifi: Init dynamic rx buffer num: 0

Kindly do reply.

Thanks,
Naeem

**Comment by tonyp7** [comment]
Check the line ESP_ERROR_CHECK(esp_wifi_set_storage(WIFI_STORAGE_RAM)); in wifi_manager.c

**Comment by snahmad** [comment]
We store our-self in NVS the WiFi settings.
This line is good enough

ESP_ERROR_CHECK(esp_wifi_set_storage(WIFI_STORAGE_RAM));
