### ISSUE TITLE
AP not visible or not started

### ISSUE THREAD

**Issue by GvTT** [tonyp7/esp32-wifi-manager#28]
Hi,

I am new to ESP32, so my apologies if I am missing out something obvious.

I downloaded the esp32-wifi-manager and tried to compile the project, using vscode, ESP-IDF 3.2 and mingw32 under windows. It compiled fine, starts and using make monitor I see the attached log.

No errors present, but I do not see any Access Point when scanning for it. Hence I cannot connect and configure the STA.

**esp_wifi_start()** in wifi_manager.c, line 577 returns ESP_OK.

I am puzzled, what the problem might be.

I m using the Heltec esp32 wifi board.

Any help appreciated.

Kind regards
GvT
[ESP_wifi_manager.txt](https://github.com/tonyp7/esp32-wifi-manager/files/2699746/ESP_wifi_manager.txt)

**Comment by tonyp7** [comment]
Hello GvTT, when you see the message:

> wifi_manager: starting softAP with ssid esp32
> wifi_manager: starting softAP with 20 MHz bandwidth
> wifi_manager: starting softAP on channel 5

It means everything worked as expected. If you have a tool like WireShark you should see the network. 

Where do you live? Maybe channel 5 is not authorized in your country.
