### ISSUE TITLE
Problem connecting iphones - esp-idf 3.1.2

### ISSUE THREAD

**Issue by eftimarco** [tonyp7/esp32-wifi-manager#30]
Hello,

With 3.1.2 esp-idf version, I'm struggling to connect iPhones to Wifi manager while it is working fine with Androids' phones.

Does anyone face the same issue ? Any tricks ?

**Comment by ictcorebiz** [comment]
Hi, I get a problem connecting my iPad, that it doesn't seem to get a good IP address... @eftimarco was this your problem as well?

**Comment by eftimarco** [comment]
Yes, it looks like this.
Is-it coming from esp stack ?

**Comment by tonyp7** [comment]
Hello,
This should be fixed in the latest commits. Tested on an iPhone 8 and worked just fine
