### ISSUE TITLE
Enhancement: Support for 802.11 LR (aka. ESP Wifi Long Range Mode)

### ISSUE THREAD

**Issue by careyer** [tonyp7/esp32-wifi-manager#45]
Hi there,

first of all "Kudos!" for such a nice project! Loving it!

I wonder if it would be possible to include support for the ESP32 WiFi Long Range Mode (https://blog.hackster.io/long-range-wifi-for-the-esp32-9429ab89f450) ?
This way this project could be used as a "WiFi LR <-to-> WiFi" Bridge and LR devices (such as ESP32 based IoT sensors and devices) could be connected to a standard Home WiFi over massive distances. That would be really nice! Distances of 1-10km can be achieved with this mode.

The WiFi-Manager would run a SoftAP with LR Mode enabled and communicate to the other WiFi networks nearby in standard WiFi Mode.

Best regards and keep up the excellent work!
Cheers!
Thomas

**Comment by tonyp7** [comment]
Hello Thomas,

Thank you for the kind words. As you might have guessed with this very late response there's no plan for this now.
