### ISSUE TITLE
How to use Event callbacks? 

### ISSUE THREAD

**Issue by pawisoon** [tonyp7/esp32-wifi-manager#49]
Hi,
I managed to flash wifi manager on my esp32. Now I would like to add functionality that will check if some pin is high state. If that is true just make a post request or connect to mqtt. 
How would I do it?

**Comment by tonyp7** [comment]
Hello,
I don't understand how this is related to event callbacks? You can just create a new thread that will hold you user code.

**Comment by pawisoon** [comment]
So after installing wifimanager I can code stuff in Arduino IDE and upload my sketch to it?

**Comment by tonyp7** [comment]
Not with Arduino IDE no; this project is an esp-idf project and must be compiled with the esp-idf toolchain.

Check https://docs.espressif.com/projects/esp-idf/en/latest/get-started/
