### ISSUE TITLE
recording problem

### ISSUE THREAD

**Issue by marocama** [tonyp7/esp32-wifi-manager#52]
Hello friends,
I'm starting to learn how to use IDF.
I am trying to write the default_demo example but it is giving the error:
"Executing" ninja all "...
[1/5] Performing build step for 'bootloader'
ninja: no work to do.
[2/3] Linking CXX executable wifi_manager.elf
FAILED: wifi_manager.elf "

I believe I am installing the wifi_manager library the wrong way.
I'm putting the "default_demo" folder and the "scr" folder in the esp_idf root, is that it?

thank you for now

**Comment by tonyp7** [comment]
I cannot comment about your build system. Using standard make all you have to do from the repository is:

```
cd examples/default_demo
make menuconfig
make -j8
```

Where the 8 in -j8 is the number of logical processors you PC has. j8 works with my i7700k.

**Comment by marocama** [comment]
Unfortunately I have this return:

"makefile: 10: /make/project.mk: No such file or directory
make: *** No rule to make target `/make/project.mk '. Stop. "

Is this related to the IDF version?

**Comment by tonyp7** [comment]
Most likely your environment is not setup correctly. Try to build any esp-idf example, for instance try "make" in esp-idf/examples/get-started/hello_world

**Comment by marocama** [comment]
Hello again,
I reinstalled the IDF, and now the project gets to build, but at the end of the build I get this message:

> esptool.py v2.8-dev
> [825/826] Linking CXX executable wifi_manager.elf
> FAILED: wifi_manager.elf
