### ISSUE TITLE
module getting restarted

### ISSUE THREAD

**Issue by Suryaobulareddy2932** [tonyp7/esp32-wifi-manager#53]
I just build the source and do run. When I'm connecting to ESP32 wifi(STA) in mobile module getting restarted

I (5903) dns_server: Replying to DNS request for idmb-app-chat-global-xiaomi-1108233833.ap-south-1.elb.amazonaws.com... from 10.10.0.2
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x4000c677  PS      : 0x00060d30  A0      : 0x800e4ad9  A1      : 0x3ffc8e00
A2      : 0x00000000  A3      : 0x3f406ef8  A4      : 0x3ffc8e58  A5      : 0x00000001
A6      : 0x00000000  A7      : 0x00060523  A8      : 0x3ffcbf3d  A9      : 0x00000000
A10     : 0x3ffc8e4b  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x00000000
A14     : 0x00000000  A15     : 0xff000000  SAR     : 0x0000001b  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff

ELF file SHA256: 7b3d40228c8d28e83ce6ff3fb53a2fdee0973d98960b768004aa153340ec50c0

Backtrace: 0x4000c674:0x3ffc8e00 |<-CORRUPTED

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6524
load:0x40078000,len:12200
load:0x40080400,len:6640
entry 0x40080774

**Comment by mgoeller** [comment]
Did you manage to solve this?
