### ISSUE TITLE
Possible feature: ability to change AP SSID & Password over webpage

### ISSUE THREAD

**Issue by sullij** [tonyp7/esp32-wifi-manager#54]
Hello, awesome work on this wifi manager btw! 

I am using the wifi manager and thought it would be great to have the ability to create a new AP ssid and password over the webpage. I was trying this, but I am having major troubles modifying the wifi_manager.c file to enable saving the new credentials to the flash and retrieving them upon restarting the ESP - so I thought I would ask if you have any plans for this in the future? 

all the best

**Comment by tonyp7** [comment]
Hello,

Thanks for the kind words. This is absolutely not in plan right now. Changing the web ui / sync with the esp is not worth it I feel. SSID will remain static but it can be changed through "make menuconfig"
