### ISSUE TITLE
no captive portal on Samsung devices

### ISSUE THREAD

**Issue by cgfoed** [tonyp7/esp32-wifi-manager#57]
While testing my current project with different devices I noticed that there is no page splash on a samsung device.

Some digging turned out, that they behave a bit special. As solution it is suggested to answer with an empty 204 packet (??). I usually don't have to deal with DNS-stuff ^^'

Anyhow - I'm trying to implement some code to catch that problem. But any help would be highly appreciated. 
I'll update this Issue as I make any progress.

readings:
https://github.com/tripflex/wifi-captive-portal/issues/7

https://community.arubanetworks.com/t5/Wireless-Access/Samsung-Captive-Portal-Detection/m-p/405934#M78972

https://lemariva.com/blog/2017/11/white-hacking-wemos-captive-portal-using-micropython

https://github.com/tripflex/captive-portal/blob/master/src/mgos_captive_portal.c
starting line 367

https://socifi-doc.atlassian.net/wiki/spaces/SC/pages/94371841/DNS+Fix+to+keep+Android+Splash+Page+and+the+Captive+Portal+Notification+active

**Comment by tonyp7** [comment]
I am testing with a Samsung Galaxy Tab A and an iPhone XS and have no issue with the Galaxy Tab.

If all it takes is registering a few end points then sure I can try doing this. Thanks for the tip from the triplex repo

**Comment by tonyp7** [comment]
This is what happens on my samsung device when I connect to the esp:

![wifi](https://idyl.io/wp-content/uploads/2019/10/Screenshot_20191013-143009_Settings-640x1024.jpg)

When I tap on "sign in to the network" I am lead to the captive portal as expected:

![captive portal](https://idyl.io/wp-content/uploads/2019/10/Screenshot_20191013-143023_CaptivePortalLogin-640x1024.jpg)

**Comment by tonyp7** [comment]
@cgfoed any update? I'll close this issue otherwise

**Comment by cgfoed** [comment]
my tests so far:

Honor with Android 9 - worked
iPhone XR - worked
iPhone SE - worked
Galaxy S7 with Android 8 - no captive portal
Galaxy S10 with  Android 9 - no captive portal
iPhone XS - worked 
ZTE #generic_model with Android 8 - worked

hopefully I can test with an Samsung A40 soon. 

Wasn't able to tackle that issue in software so far.
I created a QR-code which links to 10.10.0.1 to slap on as a sticker as workaround - which I guess is useful anyway.

**Comment by cgfoed** [comment]
no splash screen on Samsung A40.
It connect's and says there is no internet connection - thats it.

**Comment by tonyp7** [comment]
Damn it it really sucks that the only Samsung device I have actually works. Not sure what to do to test it.  I can change the code to add a 200 OK to http://connectivitycheck.gstatic.com/generate_204; which from the forum links you provided seems to trigger the captive portal.

**Comment by cgfoed** [comment]
i'll try any code changes, that you can provide.
I also was briefly thinking about sending you a used device, but sg is quite far away ^^'

**Comment by cgfoed** [comment]
I don't know why and I don't know how.
But after much trying and further reading I could solve my problem.

The answer for me was this:
https://github.com/esp8266/Arduino/pull/5529/commits/d5265aa5ac4995b65bce3e29025307cfd7ae0d0f#diff-9978b19703e34e9504dcdda781907935

A simple change to
`
/** @brief Defines the access point's default IP address. Default: "10.10.0.1 */
#define DEFAULT_AP_IP						"172.217.28.1"
`
solved all my issues with all Galaxy Devices I've tested so far.

**Comment by cgfoed** [comment]
(Maybe this is worth pointing out in the manual somewhere....)

**Comment by cgfoed** [comment]
F**k! The behavior on iPhone and other Andrioid devices is now horrible. 
So changing the default AP IP is not the solution for my problem here. But maybe I'll figure something out now.

**Comment by baldhead69** [comment]
In my samsung edge s7 no page "splash" too.

I install de lib today(01/09/2020).

**Comment by baldhead69** [comment]
This issue should be open.

**Comment by kaly7** [comment]
It work with Android 10 (Huawei)  , but android 9 not (LG K20).. any ide, why? :(
No captive portal.. if I use http://10.10.0.1 (default ip address) only wait, wait, wait... 
But have any data traffic:

I (34550) dns_server: Replying to DNS request for www.google.com from 10.10.0.2
I (37410) dns_server: Replying to DNS request for alt7-mtalk.google.com from 10.10.0.2
I (37420) dns_server: Replying to DNS request for connectivitycheck.gstatic.com from 10.10.0.2 

:(

**Comment by orlandev** [comment]
i use IP like 200.200.200.1 and its functional for mi in Samsung devices. I tested in Note8 Android 8.1

 i use this configuration and work for me. https://github.com/Qu35t64/CaptivePortal

**Comment by cgfoed** [comment]
> i use IP like 200.200.200.1 and its functional for mi in Samsung devices. I tested in Note8 Android 8.1
> 
> i use this configuration and work for me. https://github.com/Qu35t64/CaptivePortal

But does it still work for iOS and other Android devices?

**Comment by orlandev** [comment]
> > i use IP like 200.200.200.1 and its functional for mi in Samsung devices. I tested in Note8 Android 8.1
> > i use this configuration and work for me. https://github.com/Qu35t64/CaptivePortal
> 
> But does it still work for iOS and other Android devices?

yes, its work

**Comment by Inventor-X** [comment]
Hello Guys...
I have made a captive portal using apache2 server....
I am not able to see the spash screen on samsung devices..only.
I have tried everything that you all have discussed....
But no use.....
Can anyone please guide me what should i do...to get it working on samsung devices...
PLEASE.....

**Comment by Inventor-X** [comment]
> > > i use IP like 200.200.200.1 and its functional for mi in Samsung devices. I tested in Note8 Android 8.1
> > > i use this configuration and work for me. https://github.com/Qu35t64/CaptivePortal
> > 
> > 
> > But does it still work for iOS and other Android devices?
> 
> yes, its work

It is not working.....
Can you please suggest anything else......

**Comment by nan4k7** [comment]
Still no solutions?

**Comment by italocjs** [comment]
> Still no solutions?

I never figured it out 😕

**Comment by bsoroudi** [comment]
@italocjs 

This is insane. I have been trying to figure this out for 2 weeks. The solution is to use a public ip range for your hotspot network and captive portal. 

I used the 200.200.200.0/24 subnet. Works great now with samsung, iphone, motorola. 

I am using Raspberry Pi Zero 2w, Pi OS, iw to create the virtual interface used for the hotspot, NetManager for the Hotspot config and management, flask for the webserver, and writing this to resolve all dns requests to the hotspot ip
"address=/#/{self.hotspot_ip}\n"" in /etc/NetworkManager/dnsmasq-shared.d/dns.conf".

So this resolves all dns requests to your webserver which should have the endpoints listening for requests to the android, samsung, apple urls and return the 302 redirects to your captive portal url for Android or 200 for ios:

`
@app.route('/hotspot-detect.html')
        def ios_captive():
            """Handle iOS captive portal detection - returns setup page"""
            return render_template_string(HTML_TEMPLATE)
        @app.route('/generate_204')
        @app.route('/gen_204')
        def android_captive():
            """Handle Android captive portal detection.
            Return 302 redirect so Android detects captive portal; no-cache headers
            prevent the device from caching the redirect."""
            response = redirect(f"http://{self.hotspot_ip}/", code=302)
            response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
            response.headers["Pragma"] = "no-cache"
            response.headers["Expires"] = "0"
            return response
        @app.route('/connecttest.txt')
        @app.route('/redirect')
        @app.route('/ncsi.txt')
        @app.route('/connect/test')
        @app.route('/success.txt')
        def windows_captive():
            """Handle Windows captive portal detection"""
            # Windows expects plain text, but we'll return HTML to show setup page
            return render_template_string(HTML_TEMPLATE)
`

**Comment by italocjs** [comment]
> [@italocjs](https://github.com/italocjs)
> 
> This is insane. I have been trying to figure this out for 2 weeks. The solution is to use a public ip range for your hotspot network and captive portal.
> 
> I used the 200.200.200.0/24 subnet. Works great now with samsung, iphone, motorola.
> 
> I am using Raspberry Pi Zero 2w, Pi OS, iw to create the virtual interface used for the hotspot, NetManager for the Hotspot config and management, flask for the webserver, and writing this to resolve all dns requests to the hotspot ip "address=/#/{self.hotspot_ip}\n"" in /etc/NetworkManager/dnsmasq-shared.d/dns.conf".
> 
> So this resolves all dns requests to your webserver which should have the endpoints listening for requests to the android, samsung, apple urls and return the 302 redirects to your captive portal url for Android or 200 for ios:
> 
> `@app.route('/hotspot-detect.html') def ios_captive(): """Handle iOS captive portal detection - returns setup page""" return render_template_string(HTML_TEMPLATE) @app.route('/generate_204') @app.route('/gen_204') def android_captive(): """Handle Android captive portal detection. Return 302 redirect so Android detects captive portal; no-cache headers prevent the device from caching the redirect.""" response = redirect(f"http://{self.hotspot_ip}/", code=302) response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate" response.headers["Pragma"] = "no-cache" response.headers["Expires"] = "0" return response @app.route('/connecttest.txt') @app.route('/redirect') @app.route('/ncsi.txt') @app.route('/connect/test') @app.route('/success.txt') def windows_captive(): """Handle Windows captive portal detection""" # Windows expects plain text, but we'll return HTML to show setup page return render_template_string(HTML_TEMPLATE)`

Thanks for sharing, ill definitely try it out.

**Comment by Amine844** [comment]
Anyone have a solution samsung captive portal devices ,

**Comment by DansMTR** [comment]
setup:
esp32 , on espressif software v5.2 using this library:
1- Modified the "MAX HTTP REQUEST Header Length" and the "MAX HTTP URI LENGTH" , from the sdkConfig of the project... the default ones are 512 and 512 which caused the HOST to be NULL
2- configured a passthrough DNS for :
static const char* const dns_passthrough_domains[] = {
	"clients3.google.com",
	"gstatic.com",
	"connectivitycheck.android.com"
};
in order to deliberatly fail those connections, the dns server will reply to those connections with "no such address" response, which i think was the main issue with samsung and android devices.

after that : on samsung devices when connected to the esp , it will show a pop up to sign in notification, 
on other android phones (oppo.. redmi...) , and iphones and laptop, it will automatically open the captive portal.
