### ISSUE TITLE
Need to reconfiguration 

### ISSUE THREAD

**Issue by Kirankumar-xenlabs** [tonyp7/esp32-wifi-manager#62]
Hi, 

I want to erase the saved SSID and Password and I want to connect new wifi network, how should I do or I want to connect the other network how should I do for that.

Regards, 
Kirankumar

**Comment by tonyp7** [comment]
Just connect to the portal and disconnect the wifi from there.

**Comment by Kirankumar-xenlabs** [comment]
if I want to connect the new wifi network then what should i do.
