### ISSUE TITLE
sockaddr_in sa not used

### ISSUE THREAD

**Issue by qcarver** [tonyp7/esp32-wifi-manager#64]
https://github.com/tonyp7/esp32-wifi-manager/blob/2871cf1fab3fa5c60c67fcee5c0d0e0c395db34c/src/dns_server.c#L80

Hello, it looks like you grabbed some code that maybe used sa as the bind address to send to and ra as the local address you want to bind to receive on. Implementation in this method though is only using ra. You could scuttle sa if you don't have any plans for it. Thx.

**Comment by tonyp7** [comment]
You are right.

Fixed in #83
