### ISSUE TITLE
net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by matheusnatanb** [tonyp7/esp32-wifi-manager#65]
Hello, most of time I try to access the AP page from windows 10 I get this: 
![error_1](https://user-images.githubusercontent.com/51249487/73846742-caa2f380-4803-11ea-80b5-ba4bb8cac227.png)

I'm using the last stable version of esp-idf, i've also tried with previous version 3.2.3, 3.2.

I've noticed that it happens in internet browsers often.

What can i do to fix that? 

Please, someone help me.

**Comment by tonyp7** [comment]
This is solved since moving the webserver to esp_http_server
