### ISSUE TITLE
iOS 13.4 blank screen

### ISSUE THREAD

**Issue by mgoeller** [tonyp7/esp32-wifi-manager#70]
Somehow iOS13.4 and newest macOS release have an error: the wifi manager - if it connects at all - often just returns a blank page and doesn't load the html.

This [repo](https://github.com/RavenSystem/esp-homekit-devices/commit/25a06a76e314a716b5c6d97b855e8817092bd304) is using a esp8266 wifi manager and just fixed this error (or did a workaround since it may also be on apple side), however I do not understand what needs to be changed in esp32-wifi-manager.

Can anyone help?

**Comment by ginodecock** [comment]
I can report the same issue with esp32 and ios 13.4.

**Comment by mgoeller** [comment]
In another repo this was fixed for ESP8266, but I don't understand what exactly was done. Respectively I don't see the difference in any of the changes to the state before.

See: https://github.com/RavenSystem/esp-homekit-devices/releases/tag/HAA_1.9.2

**Comment by ginodecock** [comment]
I switched to ble provisioning.

**Comment by mgoeller** [comment]
Can you link me to an article / repo explaining that?

**Comment by ginodecock** [comment]
This is an example of Espressif https://github.com/espressif/esp-idf/tree/master/examples/provisioning/legacy/ble_prov

**Comment by tonyp7** [comment]
I have upgraded to iOS 13.5 from 13.2 and confirms the captive portal is no longer kicked in

**Comment by tonyp7** [comment]
@mgoeller thanks for the pointer. I really don't understand what they changed and I can't find any relevant information about what Apple changed to break the portal.

What I see is that the /GET request does not even run on the server. That means the program does not even get the chance to read the host requested.

I opened an issue on their repo and hopefully they can give some pointers.

**Comment by tonyp7** [comment]
#84 fixes this issue
