### ISSUE TITLE
Ability to save multiple AP's.

### ISSUE THREAD

**Issue by benjamintyler** [tonyp7/esp32-wifi-manager#77]
First of all, excellent work on this WiFi manager! Its by far the best WiFi manager available for the ESP32.

Once suggestion...would it be possible to add the ability to save multiple AP's? And then the WiFi manager would simply choose the best AP with the strongest RSSI?

**Comment by tonyp7** [comment]
Hello Benjamin,

Thanks for the kind words! Well yes it would be possible but that would bring a lot of complexities which are unwarranted for this type of project. Flash saving would need to be a list, this would eat more RAM to load the config. The intend of the WiFi manager is to just fire once, configure, and forget it even existed.

Keeping it as lightweight and simple as possible is its primary goal. I think this is not going to benefit a majority of users.
