### ISSUE TITLE
Compile Wifi manager with ESP32-AT command

### ISSUE THREAD

**Issue by gitsteven73** [tonyp7/esp32-wifi-manager#79]
Hello sir:

the wifi manager is good for me , thanks a lot and 
I tested it with compiled ok to EPS32-WROOM-32D, 
I would like to include it to ESP-AT command code ( https://github.com/espressif/esp-at ) , 
I just put  " wifi_manager_start(); " in begin of app_main (ESP-AT), 
after successful compiled and flash in ESP32 module, 
I got log messages from UART0 but keep reset , and display log messages again  and again.
Do you have any idea ? sorry to trouble you , have a nice day.

**Comment by tonyp7** [comment]
Hello, sorry but this is unrelated to the manager
