### ISSUE TITLE
Manual connection issue 

### ISSUE THREAD

**Issue by MoustachedBird** [tonyp7/esp32-wifi-manager#89]
When I try to use a Manual Connection (Hidden SSID) it has a problem when I click "JOIN" button nothing happens... Any Idea? 

Thank you :)

**Comment by MoustachedBird** [comment]
Sorry, it think I already solved it (i guess...), the problem seemed to be this section in the **code.js** file
```

  gel("cancel").addEventListener("click", cancel, false);

  gel("manual_cancel").addEventListener("click", cancel, false);

  gel("join").addEventListener("click", performConnect, false);

  gel("manual_join").addEventListener(
    "click",
    (e) => {
      performConnect(e.data("connect"));
    },
    false
  );
```
I only changed manual section by 

```
 gel("manual_join").addEventListener(
    "click",
    (e) => {
      performConnect("manual");
    },
    false
  );
```

**Comment by tonyp7** [comment]
I fixed a few bugs due to rewriting code.js and ditching jquery. Hopefully this is the last one. Good catch @MoustachedBird
