### ISSUE TITLE
Change to only sta mode when connected

### ISSUE THREAD

**Issue by menesesleonardo** [tonyp7/esp32-wifi-manager#9]
Skimming through the code, it seems that the expected behavior is to connect to the network via web server, being the device in sta+ap mode and change to only sta mode. But this doesn't happen

**Comment by tonyp7** [comment]
Hi,
The app doesn't close the AP once it's connected. Today it's not a feature of the app.

**Comment by tonyp7** [comment]
This is now the new behaviour in current master branch. Try it out.
